export default {
  lang: 'en',
  title: 'Aurélien Leloup — Resume',

  eyebrow: 'AVAILABLE · COPENHAGEN',
  roleStrong: 'Full-Stack Developer & Cloud Engineer',
  roleSpan: '· Java · Angular · AWS Certified',
  summaryBold1: '10 years',
  summaryText: 'building production systems for startups, scale-ups, and global enterprises — across fintech, agritech, aviation, and telco. Front-end, back-end, cloud. ',
  summaryBold2: 'AWS Solutions Architect certified.',

  sContact: 'Contact',
  sSkills: 'Skills',
  sLanguages: 'Languages',
  sCertifications: 'Certifications',
  sEducation: 'Education',
  sInvolvement: 'Additional experiences',

  languages: [
    { name: 'French',  level: 'NATIVE' },
    { name: 'English', level: 'C1 · PROFESSIONAL' },
    { name: 'Danish',  level: 'B1 · INTERMEDIATE' },
    { name: 'German',  level: 'A2' },
  ],

  certifications: [
    { year: '2024', title: 'Amazon Web Services', sub: 'Solutions Architect — Associate' },
  ],

  education: [
    { year: '2011 — 2016', title: 'INSA Toulouse', sub: 'Master of Engineering · Computer Science & Networks' },
  ],

  involvement: [
    { year: '2026 → Present', title: 'La French Tech Copenhagen', sub: 'Tech Ambassador · website contributor' },
    { year: '2024 — 2025',   title: 'EPSI',                      sub: 'Cloud Computing Lecturer · M1 AWS, Docker, Kubernetes' },
    { year: '2021 — 2023',   title: 'Medium · @AurelienLeloup',  sub: 'Tech Writer · AWS, serverless, front-end' },
  ],

  experienceTitle: 'Professional experience',
  experienceMeta: '2016 → TODAY',
  currentBadge: 'CURRENT',

  jobs: [
    {
      flagship: true,
      period: '2025 →',
      periodLine2: 'PRESENT',
      total: 'ongoing',
      company: 'Keylane',
      isCurrent: true,
      jobTitle: 'Software Engineer - Payments & Money Movement',
      contractType: 'Permanent',
      desc: "Back-end engineer on the MoneyFlow team of Plexus, Keylane's pension administration platform. We own every money movement in the system. Built the Norwegian trading flow end-to-end, enabling Plexus to expand into its third market after the Netherlands and Denmark. Also led the integration of KID numbers into the Norwegian premium-intake pipeline, the reference enabling reconciliation between incoming payments and member accounts. Working in a financial-grade quality environment: full auditability, strict transactional integrity, regulatory reporting.",
      stackBold: 'Java',
      stackRest: '· GWT · TestNG · Financial services · MS SQL',
    },
    {
      period: '2022 — 2024',
      total: '2 years 6 months',
      company: 'Syngenta',
      jobTitle: 'Full-Stack Developer & AWS DevOps',
      contractType: 'Freelance',
      desc: "Sole architect and builder of GASEL, a genomic-selection platform accelerating Syngenta's seed-breeding R&D, from cloud infrastructure to UI design. Created a multi-account serverless AWS architecture with Java / Micronaut Lambdas, Aurora PostgreSQL, CDK-managed infra, and CodePipeline CI/CD, with a Svelte front-end and an integration-test harness running real AWS services locally via Localstack. In parallel, migrated and modernized legacy applications onto Fargate / ECS with CloudFormation, dockerization, and AWS Secret Manager.",
      stackBold: 'AWS',
      stackRest: '· Java · Micronaut · Svelte · CDK · PostgreSQL · LocalStack',
    },
    {
      period: '2020 — 2024',
      total: 'part-time',
      company: 'Osteopratic',
      jobTitle: 'Tech Lead',
      contractType: 'Freelance',
      desc: "Long-term technical lead for the platform behind France's first dedicated osteopath booking app. Mobile (Ionic, iOS/Android/web), back-office, and WordPress showcase site. Built the Angular / Spring back-office from scratch, redesigned the core availability-calculation algorithm for improved mobile performance, and embedded a Vue booking module into the WordPress site to combine SEO with a reactive booking flow. Owned CI/CD and VPS deployment across the full stack.",
      stackBold: 'Angular',
      stackRest: '· Java · Spring · Vue · Ionic · Firebase · Node.js',
    },
    {
      period: '2022',
      total: '6 months',
      company: 'Air Liquide',
      jobTitle: 'Front-end Angular Developer',
      contractType: 'Freelance',
      desc: "Front-end of BPM, an internal dashboard for visualizing and simulating profitability across Air Liquide's industrial basins. NGRX state, Storybook component library, custom D3.js charts, and full API mocking, designs delivered straight from Figma.",
      stackBold: 'Angular',
      stackRest: '· NGRX · Storybook · D3.js',
    },
    {
      period: '2021',
      total: '6 months',
      company: 'Bimpli (Natixis / BPCE)',
      jobTitle: 'Full-Stack Java / Angular Developer',
      contractType: 'Freelance',
      desc: 'Sitiz platform for managing employee meal-voucher programs. Built Angular interfaces with client-side caching and developed secure Java APIs exposed via Axway API Gateway.',
      stackBold: 'Java',
      stackRest: '· Angular · Axway API Gateway · Oracle SQL',
    },
    {
      period: '2020 — 2021',
      total: '11 months',
      company: 'Orange Wholesale',
      jobTitle: 'Full-Stack Java / Angular Developer',
      contractType: 'Freelance',
      desc: "Gr@ce Exchange platform for France's national public-fiber program (RIP). Angular front-end, Spring back-end, global error-handling layer, and Cucumber end-to-end tests.",
      stackBold: 'Java',
      stackRest: '· Angular · Spring · Cucumber · PostgreSQL',
    },
    {
      period: '2020',
      total: '8 months',
      company: 'Open Airlines',
      jobTitle: 'Full-Stack Developer',
      contractType: 'Permanent',
      desc: 'Front-end migration of SkyBreathe (airline fuel-efficiency SaaS) from Backbone.js to Angular, with large-file uploads via GCS and Java / Kotlin back-end maintenance.',
      stackBold: 'Java',
      stackRest: '· Kotlin · Angular · GCP · Spring · Backbone.js',
    },
    {
      period: '2016 — 2019',
      total: '3 years 5 months',
      company: 'Quadran',
      jobTitle: 'Tech Lead',
      contractType: 'Permanent',
      desc: "Co-created appYdex, a UX measurement standard that became Quadran's core methodology, used across client engagements. Tech lead on appYuser, the SaaS platform built on top of it: full-stack development in Java and AngularJS, operating a replicated and sharded on-premise MongoDB cluster, and mentoring the engineering team. Also delivered web-performance audits and Akamai CDN integrations for enterprise clients.",
      stackBold: 'Java',
      stackRest: '· Spring · AngularJS · MongoDB · Akamai',
    },
  ],
};
