export default {
  lang: 'en',
  title: 'Aurélien Leloup — Resume',

  eyebrow: 'AVAILABLE · COPENHAGEN',
  roleStrong: 'Full-Stack & Cloud Engineer',
  roleSpan: '· Java · Angular · AWS Certified',
  summaryBold1: '10 years',
  summaryText: 'building production systems for startups, scale-ups, and global enterprises — across fintech, agritech, aviation, and telco. Front-end, back-end, cloud. ',
  summaryBold2: 'AWS Solutions Architect certified.',
  statLbl: 'years of experience',

  sContact: 'Contact',
  sSkills: 'Skills',
  sLanguages: 'Languages',
  sCertifications: 'Certifications',
  sEducation: 'Education',
  sInvolvement: 'Involvement',

  languages: [
    { name: 'French',  level: 'NATIVE' },
    { name: 'English', level: 'C1 · PROFESSIONAL' },
    { name: 'Danish',  level: 'B1 · INTERMEDIATE' },
    { name: 'German',  level: 'A2' },
  ],

  certifications: [
    { year: '2024', title: 'Amazon Web Services', sub: 'Solutions Architect — Associate' },
  ],

  education: [
    { year: '2011 — 2016', title: 'INSA Toulouse', sub: 'Master of Engineering · Computer Science & Networks' },
  ],

  involvement: [
    { year: '2026 → Present', title: 'La French Tech Copenhagen', sub: 'Tech Ambassador · website contributor' },
    { year: '2024 — 2025',   title: 'EPSI',                      sub: 'Cloud Computing Lecturer · M1 AWS, Docker, Kubernetes' },
    { year: '2021 — 2023',   title: 'Medium · @AurelienLeloup',  sub: 'Tech Writer · AWS, serverless, front-end' },
  ],

  experienceTitle: 'Professional experience',
  experienceMeta: '2016 → TODAY',
  currentBadge: 'CURRENT',

  jobs: [
    {
      flagship: true,
      period: '2025 →',
      periodLine2: 'PRESENT',
      total: 'ongoing',
      company: 'Keylane',
      isCurrent: true,
      jobTitle: 'Software Engineer',
      contractType: 'Permanent',
      desc: "Back-end engineer on the MoneyFlow team for Plexus, Keylane's pension administration platform serving major insurers across Europe — the team owns every money movement in the system. Currently leading the trading flow for the Norwegian market, adapting the platform to Norway-specific regulatory requirements.",
      stackBold: 'Java',
      stackRest: '· Spring · SQL · Microservices · Agile',
    },
    {
      period: '2022 — 2024',
      total: '2 years 6 months',
      company: 'Syngenta',
      jobTitle: 'Full-Stack Developer & AWS DevOps',
      contractType: 'Freelance',
      desc: 'Built GASEL, a serverless genomic-selection platform, from scratch in a fully AWS-native environment — multi-account CDK, Java 17 / Micronaut Lambda back-end, Svelte front-end. In parallel, led the migration of legacy applications to Fargate/ECS with CodePipeline CI/CD and Flyway database migrations.',
      stackBold: 'AWS',
      stackRest: '· Java 17 · Micronaut · Svelte · CDK · CodePipeline · PostgreSQL · Docker · Flyway',
    },
    {
      period: '2020 — 2024',
      total: 'part-time',
      company: 'Osteopratic',
      jobTitle: 'Tech Lead',
      contractType: 'Freelance',
      desc: 'Booking platform for osteopaths (Ionic mobile + web). Built the Angular / Spring Boot back-office from scratch, redesigned the availability algorithm, embedded a Vue.js module in WordPress for SEO, and set up CI/CD with automated VPS deployment.',
      stackBold: 'Angular',
      stackRest: '· Spring · Vue.js · Ionic · Firebase · Node.js · MySQL · Jenkins',
    },
    {
      period: '2022',
      total: '6 months',
      company: 'Air Liquide',
      jobTitle: 'Front-end Angular Developer',
      contractType: 'Freelance',
      desc: 'Angular front-end for a BPM dashboard — NGRX state, D3.js data visualizations, Storybook-validated component library, and mocked APIs to unblock delivery independently of back-end readiness.',
      stackBold: 'Angular',
      stackRest: '· NGRX · Storybook · D3.js · Sass · GitLab CI',
    },
    {
      period: '2021',
      total: '6 months',
      company: 'Bimpli',
      jobTitle: 'Full Stack Java / Angular Developer',
      contractType: 'Freelance',
      desc: 'Sitiz platform for employee meal vouchers — Angular interfaces with client-side caching, secure Java APIs via Axway API Gateway, and level-2 production support.',
      stackBold: 'Angular',
      stackRest: '· Java EE · Axway API Gateway · Oracle SQL',
    },
    {
      period: '2020 — 2021',
      total: '11 months',
      company: 'Orange Wholesale',
      jobTitle: 'Full Stack Java / Angular Developer',
      contractType: 'Freelance',
      desc: "Gr@ce Exchange — Angular 7 front-end and Spring Boot back-end for translating France's fiber-deployment data into Orange's internal format, with a global error-handling layer, partner API integrations, and Cucumber end-to-end tests.",
      stackBold: 'Java',
      stackRest: '· Angular · Spring Boot · Cucumber · Ansible · GitLab CI · PostgreSQL',
    },
    {
      period: '2020',
      total: '8 months',
      company: 'Open Airlines',
      jobTitle: 'Full Stack Developer',
      contractType: 'Permanent',
      desc: 'Front-end migration of SkyBreathe (airline fuel-efficiency SaaS) from Backbone.js to Angular 9, large-file uploads via GCS, and Java EE / Kotlin back-end maintenance on Spring Boot.',
      stackBold: 'Java EE',
      stackRest: '· Kotlin · Angular 9 · GCP · Spring Boot · Backbone.js',
    },
    {
      period: '2016 — 2019',
      total: '3 years 5 months',
      company: 'Quadran',
      jobTitle: 'Tech Lead',
      contractType: 'Permanent',
      desc: 'Tech lead on appYuser, a SaaS for web-performance and UX monitoring — full-stack Java EE / AngularJS, sharded on-premise MongoDB cluster, and team mentoring. Co-created the appYdex standard, a UX measurement methodology adopted internally and in client engagements. Also delivered SEO audits, CDN comparative studies, and Akamai integrations for enterprise clients.',
      stackBold: 'Java EE',
      stackRest: '· Spring · AngularJS · MongoDB · Hibernate · Jenkins',
    },
  ],
};
