export default {
  lang: 'fr',
  title: 'Aurélien Leloup — CV',

  eyebrow: 'DISPONIBLE · COPENHAGUE',
  roleStrong: 'Ingénieur Full-Stack & Cloud',
  roleSpan: '· Java · Angular · Certifié AWS',
  summaryBold1: '10 ans',
  summaryText: "de systèmes en production pour des startups, scale-ups et grands groupes — fintech, agritech, aviation, télécoms. Front-end, back-end, cloud. ",
  summaryBold2: 'Certifié AWS Solutions Architect.',

  sContact: 'Contact',
  sSkills: 'Compétences',
  sLanguages: 'Langues',
  sCertifications: 'Certifications',
  sEducation: 'Formation',
  sInvolvement: 'Engagements',

  languages: [
    { name: 'Français', level: 'NATIF' },
    { name: 'Anglais',  level: 'C1 · PROFESSIONNEL' },
    { name: 'Danois',   level: 'B1 · INTERMÉDIAIRE' },
    { name: 'Allemand', level: 'A2' },
  ],

  certifications: [
    { year: '2024', title: 'Amazon Web Services', sub: 'Solutions Architect — Associate' },
  ],

  education: [
    { year: '2011 — 2016', title: 'INSA Toulouse', sub: "Diplôme d'ingénieur · Informatique & Réseaux" },
  ],

  involvement: [
    { year: '2026 → Présent', title: 'La French Tech Copenhagen', sub: 'Ambassadeur tech · contributeur site web' },
    { year: '2024 — 2025',    title: 'EPSI',                      sub: 'Chargé de cours Cloud Computing · M1 AWS, Docker, Kubernetes' },
    { year: '2021 — 2023',    title: 'Medium · @AurelienLeloup',  sub: 'Auteur technique · AWS, serverless, front-end' },
  ],

  experienceTitle: 'Expérience professionnelle',
  experienceMeta: "2016 → AUJOURD'HUI",
  currentBadge: 'ACTUEL',

  jobs: [
    {
      flagship: true,
      period: '2025 →',
      periodLine2: 'PRÉSENT',
      total: 'en cours',
      company: 'Keylane',
      isCurrent: true,
      jobTitle: 'Ingénieur Logiciel — Paiements & Flux Financiers',
      contractType: 'CDI',
      desc: "Ingénieur back-end dans l'équipe MoneyFlow sur Plexus, la plateforme d'administration de retraites de Keylane. Notre équipe contrôle tous les mouvements financiers du système. Mise en place du flux monétaire norvégien de bout en bout, ouvrant à Plexus son troisième marché après les Pays-Bas et le Danemark. Intégration des numéros KID dans le cycle d'encaissement des primes norvégiennes, la référence permettant la réconciliation des paiements. Niveau de qualité financière : auditabilité complète et intégrité transactionnelle stricte.",
      stackBold: 'Java',
      stackRest: '· GWT · Services financiers · MS SQL',
    },
    {
      period: '2022 — 2024',
      total: '2 ans 6 mois',
      company: 'Syngenta',
      jobTitle: 'Développeur Full-Stack & AWS DevOps',
      contractType: 'Freelance',
      desc: "Architecte et développeur unique de GASEL, une plateforme de sélection génomique pour accélérer la R&D semencière de Syngenta, de l'infrastructure cloud au design UI. Architecture AWS serverless multi-comptes avec Lambdas Java / Micronaut, Aurora PostgreSQL, infra CDK, CI/CD CodePipeline, front-end Svelte et tests d'intégration exécutant les vrais services AWS en local via LocalStack. En parallèle, migration et modernisation d'applications legacy vers Fargate / ECS avec CloudFormation, dockerisation et AWS Secrets Manager.",
      stackBold: 'AWS',
      stackRest: '· Java · Micronaut · Svelte · CDK · PostgreSQL · LocalStack',
    },
    {
      period: '2020 — 2024',
      total: 'temps partiel',
      company: 'Osteopratic',
      jobTitle: 'Tech Lead',
      contractType: 'Freelance',
      desc: "Référent technique long terme de la plateforme derrière la première application de réservation dédiée aux ostéopathes en France. Mobile (Ionic, iOS/Android/web), back-office et site vitrine WordPress. Construction du back-office Angular / Spring from scratch, refonte de l'algorithme de calcul des disponibilités pour améliorer les performances mobiles, et intégration d'un module de réservation Vue dans WordPress pour combiner SEO et flux réactif. CI/CD et déploiement VPS.",
      stackBold: 'Angular',
      stackRest: '· Java · Spring · Vue · Ionic · Firebase · Node.js',
    },
    {
      period: '2022',
      total: '6 mois',
      company: 'Air Liquide',
      jobTitle: 'Développeur Front-end Angular',
      contractType: 'Freelance',
      desc: "Développement front-end de BPM, un outil interne pour visualiser et simuler la rentabilité des bassins industriels d'Air Liquide. Gestion d'états avec NGRX, bibliothèque de composants Storybook, graphiques D3.js sur-mesure, mocking complet des APIs et intégration de maquettes Figma.",
      stackBold: 'Angular',
      stackRest: '· NGRX · Storybook · D3.js',
    },
    {
      period: '2021',
      total: '6 mois',
      company: 'Bimpli (Natixis / BPCE)',
      jobTitle: 'Développeur Full Stack Java / Angular',
      contractType: 'Freelance',
      desc: "Plateforme Sitiz de gestion des programmes de chèques-restaurant pour entreprises. Interfaces Angular avec cache côté client et APIs Java sécurisées exposées via Axway API Gateway.",
      stackBold: 'Java',
      stackRest: '· Angular · Axway API Gateway · Oracle SQL',
    },
    {
      period: '2020 — 2021',
      total: '11 mois',
      company: 'Orange Wholesale',
      jobTitle: 'Développeur Full Stack Java / Angular',
      contractType: 'Freelance',
      desc: "Plateforme Gr@ce Exchange pour le programme national de déploiement de la fibre publique (RIP). Front-end Angular, back-end Spring, couche de gestion globale des erreurs et tests end-to-end Cucumber.",
      stackBold: 'Java',
      stackRest: '· Angular · Spring · Cucumber · PostgreSQL',
    },
    {
      period: '2020',
      total: '8 mois',
      company: 'Open Airlines',
      jobTitle: 'Développeur Full Stack',
      contractType: 'CDI',
      desc: "Migration front-end de SkyBreathe (SaaS d'efficacité carburant pour compagnies aériennes) de Backbone.js vers Angular, avec uploads de fichiers volumineux via GCS et maintenance du back-end Java / Kotlin.",
      stackBold: 'Java',
      stackRest: '· Kotlin · Angular · GCP · Spring · Backbone.js',
    },
    {
      period: '2016 — 2019',
      total: '3 ans 5 mois',
      company: 'Quadran',
      jobTitle: 'Tech Lead',
      contractType: 'CDI',
      desc: "Co-création d'appYdex, un standard de mesure UX devenu la méthodologie centrale de Quadran, déployé dans les missions clients. Tech lead sur appYuser, le SaaS principal de Quadran : développement full-stack Java / AngularJS, exploitation d'un cluster MongoDB on-premise répliqué et shardé, et mentorat de l'équipe. Audits de performance web et intégrations CDN Akamai pour des clients grands comptes.",
      stackBold: 'Java',
      stackRest: '· Spring · AngularJS · MongoDB · Akamai',
    },
  ],
};
