export default {
  lang: 'fr',
  title: 'Aurélien Leloup — CV',

  eyebrow: 'DISPONIBLE · COPENHAGUE',
  roleStrong: 'Ingénieur Full-Stack & Cloud',
  roleSpan: '· Java · Angular · Certifié AWS',
  summaryBold1: '10 ans',
  summaryText: "de systèmes en production pour des startups, scale-ups et grands groupes — fintech, agritech, aviation, télécoms. Front-end, back-end, cloud. ",
  summaryBold2: 'Certifié AWS Solutions Architect.',
  statLbl: "ans d'expérience",

  sContact: 'Contact',
  sSkills: 'Compétences',
  sLanguages: 'Langues',
  sCertifications: 'Certifications',
  sEducation: 'Formation',
  sInvolvement: 'Engagements',

  languages: [
    { name: 'Français', level: 'NATIF' },
    { name: 'Anglais',  level: 'C1 · PROFESSIONNEL' },
    { name: 'Danois',   level: 'B1 · INTERMÉDIAIRE' },
    { name: 'Allemand', level: 'A2' },
  ],

  certifications: [
    { year: '2024', title: 'Amazon Web Services', sub: 'Solutions Architect — Associate' },
  ],

  education: [
    { year: '2011 — 2016', title: 'INSA Toulouse', sub: "Diplôme d'ingénieur · Informatique & Réseaux" },
  ],

  involvement: [
    { year: '2026 → Présent', title: 'La French Tech Copenhagen', sub: 'Ambassadeur tech · contributeur site web' },
    { year: '2024 — 2025',    title: 'EPSI',                      sub: 'Chargé de cours Cloud Computing · M1 AWS, Docker, Kubernetes' },
    { year: '2021 — 2023',    title: 'Medium · @AurelienLeloup',  sub: 'Auteur technique · AWS, serverless, front-end' },
  ],

  experienceTitle: 'Expérience professionnelle',
  experienceMeta: "2016 → AUJOURD'HUI",
  currentBadge: 'ACTUEL',

  jobs: [
    {
      flagship: true,
      period: '2025 →',
      periodLine2: 'PRÉSENT',
      total: 'en cours',
      company: 'Keylane',
      isCurrent: true,
      jobTitle: 'Ingénieur Logiciel',
      contractType: 'CDI',
      desc: "Ingénieur back-end dans l'équipe MoneyFlow sur Plexus, la plateforme d'administration des retraites de Keylane utilisée par les grands assureurs européens — l'équipe gère l'ensemble des flux financiers du système. Pilote actuellement le flux trading pour le marché norvégien, en adaptant la plateforme aux exigences réglementaires locales.",
      stackBold: 'Java',
      stackRest: '· Spring · SQL · Microservices · Agile',
    },
    {
      period: '2022 — 2024',
      total: '2 ans 6 mois',
      company: 'Syngenta',
      jobTitle: 'Développeur Full-Stack & AWS DevOps',
      contractType: 'Freelance',
      desc: "Construction de GASEL, une plateforme serverless de sélection génomique, from scratch dans un environnement 100% AWS natif — CDK multi-comptes, back-end Java 17 / Micronaut Lambda, front-end Svelte. En parallèle, pilotage de la migration d'applications legacy vers Fargate/ECS avec CI/CD CodePipeline et migrations Flyway.",
      stackBold: 'AWS',
      stackRest: '· Java 17 · Micronaut · Svelte · CDK · CodePipeline · PostgreSQL · Docker · Flyway',
    },
    {
      period: '2020 — 2024',
      total: 'temps partiel',
      company: 'Osteopratic',
      jobTitle: 'Tech Lead',
      contractType: 'Freelance',
      desc: "Plateforme de réservation pour ostéopathes (Ionic mobile + web). Construction du back-office Angular / Spring Boot from scratch, refonte de l'algorithme de disponibilité, intégration d'un module Vue.js dans WordPress pour le SEO, et mise en place du CI/CD avec déploiement VPS automatisé.",
      stackBold: 'Angular',
      stackRest: '· Spring · Vue.js · Ionic · Firebase · Node.js · MySQL · Jenkins',
    },
    {
      period: '2022',
      total: '6 mois',
      company: 'Air Liquide',
      jobTitle: 'Développeur Front-end Angular',
      contractType: 'Freelance',
      desc: "Front-end Angular pour un tableau de bord BPM — état NGRX, visualisations de données D3.js, bibliothèque de composants validée par Storybook, et APIs mockées pour débloquer la livraison indépendamment du back-end.",
      stackBold: 'Angular',
      stackRest: '· NGRX · Storybook · D3.js · Sass · GitLab CI',
    },
    {
      period: '2021',
      total: '6 mois',
      company: 'Bimpli',
      jobTitle: 'Développeur Full Stack Java / Angular',
      contractType: 'Freelance',
      desc: "Plateforme Sitiz pour les tickets-restaurant — interfaces Angular avec cache côté client, APIs Java sécurisées via Axway API Gateway, et support production niveau 2.",
      stackBold: 'Angular',
      stackRest: '· Java EE · Axway API Gateway · Oracle SQL',
    },
    {
      period: '2020 — 2021',
      total: '11 mois',
      company: 'Orange Wholesale',
      jobTitle: 'Développeur Full Stack Java / Angular',
      contractType: 'Freelance',
      desc: "Gr@ce Exchange — front-end Angular 7 et back-end Spring Boot pour convertir les données de déploiement fibre en France vers le format interne d'Orange, avec une couche de gestion globale des erreurs, intégrations d'APIs partenaires et tests Cucumber end-to-end.",
      stackBold: 'Java',
      stackRest: '· Angular · Spring Boot · Cucumber · Ansible · GitLab CI · PostgreSQL',
    },
    {
      period: '2020',
      total: '8 mois',
      company: 'Open Airlines',
      jobTitle: 'Développeur Full Stack',
      contractType: 'CDI',
      desc: "Migration front-end de SkyBreathe (SaaS d'efficacité carburant pour compagnies aériennes) de Backbone.js vers Angular 9, uploads de fichiers volumineux via GCS, et maintenance du back-end Java EE / Kotlin sur Spring Boot.",
      stackBold: 'Java EE',
      stackRest: '· Kotlin · Angular 9 · GCP · Spring Boot · Backbone.js',
    },
    {
      period: '2016 — 2019',
      total: '3 ans 5 mois',
      company: 'Quadran',
      jobTitle: 'Tech Lead',
      contractType: 'CDI',
      desc: "Tech lead sur appYuser, un SaaS de monitoring de performance web et UX — full-stack Java EE / AngularJS, cluster MongoDB on-premise shardé, et mentorat d'équipe. Co-création du standard appYdex, une méthodologie de mesure UX adoptée en interne et dans les missions clients. Audits SEO, études comparatives CDN et intégrations Akamai pour des clients grands comptes.",
      stackBold: 'Java EE',
      stackRest: '· Spring · AngularJS · MongoDB · Hibernate · Jenkins',
    },
  ],
};
